//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_ADB_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Tanks
    {
        public Tanks()
        {
            this.Operations = new HashSet<Operations>();
        }
		[Key]
		[Display(Name = "Номер емкости")]
        public int TankID { get; set; }
        [Display(Name = "Тип емкости")]
        public string TankType { get; set; }
        [Display(Name = "Объем емкости")]
        public Nullable<float> TankVolume { get; set; }
        [Display(Name = "Вес емкости")]
        public Nullable<float> TankWeight { get; set; }
        [Display(Name = "Материал емкости")]
        public string TankMaterial { get; set; }
        public virtual ICollection<Operations> Operations { get; set; }
    }
}
